flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12
- skylighting-0.12
- doctemplates-0.10
- git: https://github.com/jgm/texmath.git
  commit: 9243169ebf84fb555d37750b0cf758c1cf9827dc
- git: https://github.com/jgm/pandoc-types.git
  commit: 39048c9be4922771b378154f72557a5a57739d37
- git: https://github.com/jgm/commonmark-hs.git
  commit: bb866b569618f7a9c12579f608116bf60010c9ac
  subdirs:
  - commonmark-pandoc
- git: https://github.com/jgm/citeproc.git
  commit: 22d5755231c97f749f2df4ec7eca639d6cc9c891
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]


